export { default as About } from './About';
export { default as Blogs } from './Blogs';
export { default as Contact } from './Contact';
export { default as Experiences } from './Experiences';
export { default as Pricing } from './Pricing';
export { default as Services } from './Services';
export { default as Works } from './Works';
export { default as Header } from './Header';
export { default as HeroSection } from './HeroSection';
